# typed: false
# frozen_string_literal: true

# Homebrew Formula for sym - Symbolic Link Manager
class Sym < Formula
  desc "User-friendly symbolic link manager for ~/.local/bin"
  homepage "https://github.com/11ways/sym"
  url "https://github.com/11ways/sym/archive/refs/tags/v1.1.0.tar.gz"
  sha256 "1b5bcd7dbf9ea6b9589c54efec6dde84cf5cafa0a185e344f1440d6bb2780256"
  license "MIT"
  head "https://github.com/11ways/sym.git", branch: "main"

  def install
    # Install the main script
    bin.install "sym.sh" => "sym"

    # Install pre-built man page
    man1.install "sym.1.gz"

    # Install shell completions generated by the CLI itself.
    generate_completions_from_executable(bin/"sym", "completion")
  end

  test do
    # Test that the script runs
    assert_match "sym version", shell_output("#{bin}/sym --version")

    # Test basic functionality
    system "#{bin}/sym", "--help"

    # Completion output should be non-empty for each supported shell.
    assert_match "sym", shell_output("#{bin}/sym completion bash")
    assert_match "sym", shell_output("#{bin}/sym completion zsh")
    assert_match "sym", shell_output("#{bin}/sym completion fish")
  end
end
